### ISSUE TITLE
Yubikey Neo key size

### ISSUE THREAD

**Issue by rufoa** [herlo/ssh-gpg-smartcard-config#2]
Am I to understand that you were able to generate three 3072-bit subkeys on a Yubikey Neo? I didn't think this was possible - [the hardware supposedly only supports 2048-bit keys](https://github.com/Yubico/ykneo-openpgp/issues/2#issuecomment-19903568).

Could you confirm when you purchased the Neo you used to do this, please?

**Comment by nbebout** [comment]
YubiKey NEO only supports RSA2048 keys.

**Comment by nbebout** [comment]
The part talking about 3072 must have been copied from the Gemalto USB Shell Token section.  And actually it supports 4096 RSA keys.
